# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: yarn-nm
  namespace: yarn-cluster
  labels:
    component: yarn-nm
spec:
  ports:
  - port: 8088
    name: web
  - port: 8082
    name: web2
  # *.yarn-nm.yarn-cluster.svc.cluster.local
  clusterIP: None
  selector:
    component: yarn-nm
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: yarn-nm
spec:
  serviceName: "yarn-nm"
  replicas: 2
  template:
    metadata:
      labels:
        component: yarn-nm
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: yarn-nm
        image: danisla/hadoop:2.7.2
        ports:
        - containerPort: 8088
          name: web
        command:
           - "/bin/bash"
           - "/tmp/hadoop-config/bootstrap.sh"
           - "-d"
        resources:
          requests:
            memory: "1024Mi"
            cpu: "100m"
          limits:
            memory: "2048Mi"
            cpu: "4000m"
        env:
          - name: MY_CPU_LIMIT
            valueFrom:
              resourceFieldRef:
                containerName: yarn-nm
                resource: limits.cpu
                divisor: 1
          - name: MY_MEM_LIMIT
            valueFrom:
              resourceFieldRef:
                containerName: yarn-nm
                resource: limits.memory
                divisor: 1M
        volumeMounts:
          - name: hadoop-config
            mountPath: /tmp/hadoop-config
      volumes:
        - name: hadoop-config
          configMap:
            name: hadoop-config
